---
title: "RWorksheets#3a"
output: pdf_document
date: "2023-10-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```








```{r}



uppercase_LETTERS <- LETTERS[1:26]
uppercase_LETTERS
lowercase_letters <- letters[1:26]
lowercase_letters

#a. You need to produce a vector that contains the first 11 letters.
upperLetters <- LETTERS[1:11]
upperLetters

#b. Produce a vector that contains the odd numbered letters.
oddLetters <- uppercase_LETTERS[c(TRUE, FALSE)]
print(oddLetters)

#c. Produce a vector that contains the vowels
vowel_LETTERS <- LETTERS[c(1,5,9,15,21)]
vowel_LETTERS

#for vector letters
#d. Produce a vector that contains the last 5 lowercase letters.
lowerLetters <- letters[22:26]
lowerLetters

#e. Produce a vector that contains letters between 15 to 24 letters in lowercase.
lowerLetters <- letters[15:24]
lowerLetters


#2. Create a vector(not a dataframe) with the average temperatures in April for Tuguegarao City, Manila, Iloilo City, Tacloban, Samal Island, and Davao City. The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees.

#a.What is the R code and its result for creating a character vector for the city/town of Tuguegarao City, Manila, Iloilo City, Tacloban,Samal Island, and Davao City? Name the object as city. The names should follow the same order as in the instruction.

city <- c("Tuguegarao City", "Manila", "Iloilo City","Tacloban", "Samal Island", "Davao City" )
city

#b. What is the R code and its result for creating a character vector for the city/town of Tuguegarao City, Manila, Iloilo City, Tacloban,Samal Island, and Davao City? Name the object as city. The names should follow the same order as in the instruction.

temp <- c(42,39,34,34,40,27)
temp


#c. What is the R code and its result for creating a character vector for the city/town of Tuguegarao City, Manila, Iloilo City, Tacloban,Samal Island, and Davao City? Name the object as city. The names should follow the same order as in the instruction.

AverageTemp <- data.frame (city, temp)
AverageTemp


  
#d.What is the R code and its result for creating a character vector for the city/town of Tuguegarao City, Manila, Iloilo City, Tacloban,Samal Island, and Davao City? Name the object as city. The names should follow the same order as in the instruction.

names(AverageTemp) <- c("City", "Temperature" )
AverageTemp


#e. What is the R code and its result for creating a character vector for the city/town of Tuguegarao City, Manila, Iloilo City, Tacloban,Samal Island, and Davao City? Name the object as city. The names should follow the same order as in the instruction.

str(AverageTemp)  
  

#f.What is the R code and its result for creating a character vector for the city/town of Tuguegarao City, Manila, Iloilo City, Tacloban,Samal Island, and Davao City? Name the object as city. The names should follow the same order as in the instruction.

AverageTemp[3:4,1:2]

#g.

max_temp_city <- AverageTemp[which.max(AverageTemp$Temperature), "City"]
min_temp_city <- AverageTemp[which.min(AverageTemp$Temperature), "City"]

max_temp_city
min_temp_city


  
  # Using Matrices
  
#2. Create a matrix of one to eight and eleven to fourteen with four columns and three rows.
  
  #a. 
  
matrix(c(1:8, 11:14), ncol = 4, nrow = 3 )

 #b.

2*matrix(c(1:8, 11:14), ncol = 4, nrow = 3 )


#c.

matrix(c(1:8, 11:14), ncol = 4, nrow = 3 )[2,]


#d.

matrix(c(1:8, 11:14), ncol = 4, nrow = 3 )[1:2,3:4]


#e.
matrix(c(1:8, 11:14), nrow = 3, ncol = 4)[3, 2:3]

#f.
matrix(c(1:8, 11:14), nrow = 3, ncol = 4)[, 4]

#g.

matrices <- 2* matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
rownames(matrices) <- c("isa", "dalawa", "tatlo")
colnames(matrices) <- c("uno", "dos", "tres", "quatro")
matrices

#h.
new_matrices <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
dim(new_matrices) <- c(6, 2)
new_matrices



  
# Using Arrays
  
  #3. An array contains 1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1
  
 #a. 
  
data_ace <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)

array_value <- array(c(1:3, 6:9,0,3:5,1), c(2,4,3))
array_value
  

#b. 

dim(array_value)
#c.

data_ace <- c(1:3, 6:9, 0, 3:5, 1)
array_value <- array(data_ace, dim = c(2, 4, 3))

dimnames(array_value) <- list(
  c("a", "b"),
  c("A", "B", "C", "D"),
  c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array")
)

array_value


````








